---
#############################
#############################
##     JS Linter Rules     ##
##     Mr Coxall           ##
#############################
#############################

############
# Env Vars #
############
env:
  browser: true
  es6: true
  jest: true

###############
# Global Vars #
###############
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

###############
# Parser vars #
###############
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2018
  sourceType: module

###########
# Extends #
###########
extends:
  - "prettier"

###########
# Plugins #
###########
plugins:
  - "@typescript-eslint"
  - "prettier"

#########
# Rules #
#########
rules:
  {
    "require-jsdoc":
      [
        "error",
        {
          "require":
            {
              "FunctionDeclaration": true,
              "MethodDefinition": true,
              "ClassDeclaration": true,
              "ArrowFunctionExpression": true,
              "FunctionExpression": true,
            },
        },
      ],
  }
